[package]
name = "rustredis"
version = "0.1.0"
authors = ["Syed Ghufran Hassan <syedghufranhassan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "main"
path = "/app/main.rs"
[dependencies]

