name:                hs-redis-clone
version:             0.1.0.0
license:             BSD3

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5
- network
- bytestring
# We recommend using attoparsec for your parsing needs while implementing the RESP
# parser, but the final call is upto you!
- attoparsec

executables:
  hs-redis-clone-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
